// Relative paths to image assets used by the print-customizer and ARC story.
window.__resources = {
  "hoodie": "images/hoodie.jpg",
  "notebook": "images/notebook.jpg",
  "phone": "images/phone.jpg",
  "delulu": "images/delulu.jpg",
  "mug": "images/mug.jpg",
  "banner": "images/banner.jpg",
  "scarf": "images/scarf.jpg",
  "tote": "images/tote.jpg",
  "avatar": "images/avatar.jpg",
  "yuna": "images/yuna.jpg",
  "yuzu": "images/yuzu.jpg",
  "sakamoto": "images/sakamoto.jpg",
  "arc1": "images/arc1.jpg",
  "arc2": "images/arc2.jpg",
  "arc3": "images/arc3.jpg",
  "arc4": "images/arc4.jpg",
  "arc5": "images/arc5.jpg",
  "arc6": "images/arc6.jpg",
  "arc7": "images/arc7.jpg",
  "arc8": "images/arc8.jpg",
  "arc9": "images/arc9.jpg",
  "arc10": "images/arc10.jpg",
  "delulu_p1": "images/delulu_p1.jpg",
  "delulu_p2": "images/delulu_p2.jpg",
  "delulu_tshirt": "images/delulu_tshirt.jpg",
  "delulu_hoodie": "images/delulu_hoodie.jpg",
  "delulu_pants": "images/delulu_pants.jpg",
  "delulu_shoes": "images/delulu_shoes.jpg",
  "delulu_bag": "images/delulu_bag.jpg",
  "delulu_phonecase": "images/delulu_phonecase.jpg"
};
